// ════════════════════════════════════════════════════════════════════
//  SHARED STYLES — Reusable inline style objects
// ════════════════════════════════════════════════════════════════════

import { C } from "./tokens";

export const S = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.35)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 560,
    maxHeight: "88vh",
    overflowY: "auto",
    boxShadow: "0 20px 60px rgba(0,0,0,.15)",
  },
  label: {
    fontSize: 11.5,
    fontWeight: 600,
    color: C.sec,
    marginBottom: 3,
    display: "block",
    letterSpacing: ".3px",
    textTransform: "uppercase",
  },
  inp: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    border: `1.5px solid ${C.bdr}`,
    fontSize: 13,
    fontFamily: "inherit",
    outline: "none",
    marginBottom: 10,
    background: "#fff",
  },
  sel: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    border: `1.5px solid ${C.bdr}`,
    fontSize: 13,
    fontFamily: "inherit",
    outline: "none",
    marginBottom: 10,
    background: "#fff",
    cursor: "pointer",
  },
  btn: (bg, col) => ({
    padding: "8px 18px",
    borderRadius: 10,
    border: "none",
    background: bg,
    color: col,
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "opacity .15s",
  }),
  btnO: (col) => ({
    padding: "6px 14px",
    borderRadius: 8,
    border: `1.5px solid ${col || C.bdr}`,
    background: "transparent",
    color: col || C.sec,
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  }),
  card: { background: C.card, borderRadius: 14, padding: 16 },
  tag: (bg, col) => ({
    display: "inline-flex",
    padding: "2px 9px",
    borderRadius: 10,
    fontSize: 10,
    fontWeight: 600,
    background: bg,
    color: col,
    lineHeight: "18px",
  }),
  row: { display: "flex", alignItems: "center", gap: 8 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10 },
  section: { borderTop: `1px solid ${C.bdr}`, marginTop: 14, paddingTop: 14 },
};
